
# active profile
spring:
  profiles:
    activate:
      on-profile: prod

  # DB
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSSWORD}
  # JPA
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL10DialectDialect
      format_sql: true
      ddl-auto: create
#    database-platform: org.hibernate.dialect.MariaDBDialect
  #REDIS
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    session:
      store-type: redis
      redis:
        flush-mode: on_save

