
spring:
  security:
    oauth2:
      client:
        # registration
        registration:
          # GOOGLE oauth2 setting
          google:
            client-id: 679763953832-f9llpoad5hml911lf4h9rd0sjrhmr6vl.apps.googleusercontent.com
            client-secret: dbM44BWbqBYRXDzM1sH_Mg4r
            scope:
              - profile
              - email

          # NAVER oauth2 setting
          naver:
            client-id: j_BrK8OLZwOH65XpyZ4J
            client-secret: F616A7CN0x
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope: name,email,profile_image
            client-name: Naver

        # provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
