
server:
  port: $PORT


spring:
  profiles:
    include: oauth

  messages:
    basename: messages,config,i18n.messages
    encoding: UTF-8

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: debug

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker.cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false







