name: bebeShare_Deploy

on:
  push:
    branches: [ develop , main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: java setup
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 2cef82ac-8ff5-4613-b629-9a207e1f4c2a
          heroku_app_name: bebeshare-deploy
          heroku_email: blood_nail@naver.com
          justlogin: true





